//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignment()
        {
            this.SSAssignments = new HashSet<SSAssignment>();
        }
    
        public int Id { get; set; }
        public int SCId { get; set; }
        public string Name { get; set; }
        public System.DateTime DueDate { get; set; }
        public int Status { get; set; }
        public int TotalMarks { get; set; }
        public int Weightage { get; set; }
        public string FilePath { get; set; }
    
        public virtual Lookup Lookup { get; set; }
        public virtual SectionCourse SectionCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSAssignment> SSAssignments { get; set; }
    }
}
