//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagmentSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB34Entities : DbContext
    {
        public DB34Entities()
            : base("name=DB34Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<Fee> Fees { get; set; }
        public virtual DbSet<Lookup> Lookups { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<SectionCourse> SectionCourses { get; set; }
        public virtual DbSet<SectionStudent> SectionStudents { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<FeesStudent> FeesStudents { get; set; }
        public virtual DbSet<LookupCategory> LookupCategories { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<SalaryPaid> SalaryPaids { get; set; }
        public virtual DbSet<SCTime> SCTimes { get; set; }
        public virtual DbSet<SSAssignment> SSAssignments { get; set; }
        public virtual DbSet<SSExam> SSExams { get; set; }
        public virtual DbSet<StudentAttendance> StudentAttendances { get; set; }
        public virtual DbSet<TeacherAttendance> TeacherAttendances { get; set; }
    }
}
