//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeesStudent
    {
        public int FeeId { get; set; }
        public string StudentId { get; set; }
        public int AmountPaid { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public int Id { get; set; }
    
        public virtual Fee Fee { get; set; }
        public virtual Student Student { get; set; }
    }
}
